services:
  task:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
      - my_media:/files/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A todo_list worker -l INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - task
      - redis

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:$PGDATA

  redis:
    image: "redis:alpine"

volumes:
  postgres_db:
  my_media:
