# Generated by Django 5.1.1 on 2024-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
